// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/matrixops/ops_test.go
//
// Generated by this command:
//
//	mockgen -source ./internal/matrixops/ops_test.go -package mocks -destination ./internal/matrixops/mocks/mock_ops_test.go
//
// Package mocks is a generated GoMock package.
package mocks
